if(EXISTS "/home/runner/work/fuelflux/fuelflux/build-test/fuelflux_tests[1]_tests.cmake")
  include("/home/runner/work/fuelflux/fuelflux/build-test/fuelflux_tests[1]_tests.cmake")
else()
  add_test(fuelflux_tests_NOT_BUILT fuelflux_tests_NOT_BUILT)
endif()
