#!/usr/bin/env python3
# Copyright (C) 2025, 2026 Maxim [maxirmx] Samsonov (www.sw.consulting)
# All rights reserved.
# This file is a part of fuelflux application.

"""Generate the compiled FuelFlux ST bitmap tables from Terminus BDF strikes.

The input files are Terminus Font 4.49.1 ter-u12n.bdf and ter-u28b.bdf.
The generated font is a Modified Version under the SIL Open Font License 1.1
and is named "FuelFlux ST Bitmap" to avoid the reserved font name.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class BdfFont:
    width: int
    height: int
    glyphs: dict[int, tuple[int, ...]]


def parse_bdf(path: Path) -> BdfFont:
    lines = path.read_text(encoding="ascii").splitlines()
    width = height = 0
    glyphs: dict[int, tuple[int, ...]] = {}
    encoding: int | None = None
    bitmap_rows: list[int] | None = None

    for line in lines:
        if line.startswith("FONTBOUNDINGBOX "):
            _, raw_width, raw_height, _, _ = line.split()
            width = int(raw_width)
            height = int(raw_height)
        elif line.startswith("STARTCHAR "):
            encoding = None
            bitmap_rows = None
        elif line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line == "BITMAP":
            bitmap_rows = []
        elif line == "ENDCHAR":
            if encoding is not None and encoding >= 0 and bitmap_rows is not None:
                if len(bitmap_rows) != height:
                    raise ValueError(
                        f"{path}: U+{encoding:04X} has {len(bitmap_rows)} rows, "
                        f"expected {height}"
                    )
                glyphs[encoding] = tuple(bitmap_rows)
            encoding = None
            bitmap_rows = None
        elif bitmap_rows is not None:
            storage_bits = len(line) * 4
            if storage_bits < width:
                raise ValueError(f"{path}: bitmap row is narrower than {width} pixels")
            bitmap_rows.append(int(line, 16) >> (storage_bits - width))

    if width <= 0 or height <= 0 or not glyphs:
        raise ValueError(f"{path}: invalid or empty BDF font")
    return BdfFont(width=width, height=height, glyphs=glyphs)


def selected_codepoints(font: BdfFont) -> list[int]:
    return sorted(
        codepoint
        for codepoint in font.glyphs
        if 0x20 <= codepoint <= 0x7E or 0x0400 <= codepoint <= 0x04FF
    )


def format_values(values: list[int], formatter, per_line: int = 12) -> str:
    rows = []
    for offset in range(0, len(values), per_line):
        chunk = values[offset : offset + per_line]
        rows.append("    " + ", ".join(formatter(value) for value in chunk) + ",")
    return "\n".join(rows)


def generate(small_path: Path, large_path: Path, output_path: Path) -> None:
    small = parse_bdf(small_path)
    large = parse_bdf(large_path)
    if (small.width, small.height) != (6, 12):
        raise ValueError(f"small strike is {small.width}x{small.height}, expected 6x12")
    if (large.width, large.height) != (14, 28):
        raise ValueError(f"large strike is {large.width}x{large.height}, expected 14x28")

    small_codepoints = selected_codepoints(small)
    large_codepoints = selected_codepoints(large)
    if small_codepoints != large_codepoints:
        raise ValueError("small and large strikes expose different selected codepoints")
    for required in (ord("?"), 0x0401, 0x0410, 0x0451):
        if required not in small_codepoints:
            raise ValueError(f"required glyph U+{required:04X} is missing")

    small_rows = [row for cp in small_codepoints for row in small.glyphs[cp]]
    large_rows = [row for cp in small_codepoints for row in large.glyphs[cp]]

    output = f"""// Generated by tools/generate_st_bitmap_font.py from Terminus Font 4.49.1.
//
// Copyright (C) 2020 Dimitar Toshkov Zhekov.
// This is a Modified Version named \"FuelFlux ST Bitmap\" and is licensed
// under the SIL Open Font License, Version 1.1. See
// third_party/fuelflux-st-bitmap/OFL.txt and NOTICE.md.

#include <array>
#include <cstddef>
#include <cstdint>

namespace fuelflux::display::st_bitmap_font_data {{

inline constexpr char kFontName[] = \"FuelFlux ST Bitmap\";
inline constexpr std::size_t kGlyphCount = {len(small_codepoints)};
inline constexpr int kSmallWidth = {small.width};
inline constexpr int kSmallHeight = {small.height};
inline constexpr int kLargeWidth = {large.width};
inline constexpr int kLargeHeight = {large.height};

inline constexpr std::array<std::uint16_t, kGlyphCount> kCodepoints{{{{
{format_values(small_codepoints, lambda value: f'0x{value:04X}')}
}}}};

inline constexpr std::array<std::uint8_t, kGlyphCount * kSmallHeight> kSmallRows{{{{
{format_values(small_rows, lambda value: f'0x{value:02X}')}
}}}};

inline constexpr std::array<std::uint16_t, kGlyphCount * kLargeHeight> kLargeRows{{{{
{format_values(large_rows, lambda value: f'0x{value:04X}', per_line=10)}
}}}};

}} // namespace fuelflux::display::st_bitmap_font_data
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("small_bdf", type=Path)
    parser.add_argument("large_bdf", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.small_bdf, args.large_bdf, args.output)


if __name__ == "__main__":
    main()
